spring:
  datasource:
    url: jdbc:h2:mem:corsisti 
    driverClassName: org.h2.Driver
    username: sa
    password: rest                   
  h2:
    console:
      enabled: true                                  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect